services:
  - type: web
    name: oilph
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: OilPH
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://oilph.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
